# netlify.toml
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
  minify = true
[build.processing.images] 
 compress  =  true 
  compress = true
[build.processing.json]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
  minify = true
for = "/*.*"
    [headers.values]
    cache-control = "public,max-age=31536000"

 [build.processing.webp] 
 compress  =  true 
  compress = true

 
